# Generated by Django 6.0.1 on 2026-01-30 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_alter_memo_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['-created_at'], 'verbose_name': '메모', 'verbose_name_plural': '메모들'},
        ),
        migrations.RemoveField(
            model_name='memo',
            name='author',
        ),
        migrations.AddField(
            model_name='memo',
            name='category',
            field=models.CharField(choices=[('life', '생활'), ('work', '업무'), ('study', '학습'), ('event', '이벤트'), ('temp', '임시')], default='temp', max_length=10, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='memo',
            name='confidence',
            field=models.FloatField(default=0.0, verbose_name='예측 신뢰도'),
        ),
        migrations.AddField(
            model_name='memo',
            name='title',
            field=models.CharField(default='제목 없음', max_length=200, verbose_name='제목'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='키워드'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
