# Generated by Django 6.0.1 on 2026-01-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_alter_memo_options_remove_memo_author_memo_category_and_more'),
        ('memo', '0003_category_memo_category'),
    ]

    operations = [
    ]
